version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      # - WEBHOOK_TUNNEL_URL=${NGROK_URL}
      - TZ=Europe/Paris
    volumes:
      - ./credentials:/home/node/.n8n
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http n8n:5678
    depends_on:
      - n8n
    ports:
      - "4040:4040"
